backend:
  name: git-gateway
  branch: main
  #repo: taoguangc/astro-decapcms #replace with your githu repo
  #publish_mode: editorial_workflow
  #squash_merges: true
  #open_authoring: true
media_folder: 'src/assets/images' # 文件将被存储在仓库中的位置
public_folder: 'src/assets/images' # 上传媒体文件的 src 属性
site_url: 'https://astro5-decap.netlify.app/' # your site name
collections:
  - name: 'blog' # 用于路由，例如，/admin/collections/blog
    label: 'Blog' # 在 UI 中使用
    folder: 'src/content/blog' # 存储文档的文件夹路径
    create: true # 允许用户在此集合中创建新文档
    slug: '{{slug}}'
    fields: # 每个文档的字段，通常在 front matter 中
      - { label: '标题', name: 'title', widget: 'string' }
      - { label: '发布日期', name: 'date', widget: 'datetime' }
      - { label: '缩略图', name: 'thumbnail', widget: 'image' }
      - { label: '正文', name: 'body', widget: 'markdown' }
